### ISSUE TITLE
Add "Administrator" role to process public datasets

### ISSUE THREAD

**Issue by cirisjl** [cirisjl/Machine-learning-development-environment-for-single-cell-sequencing-data-analyses#13]
1. Add administer role to process public datasets. Administrators can choose to publish the dataset in either public or their private storage. 
2. Add public storage for public datasets.
3. All users can select public datasets.
4. Once the user chooses the public dataset, there should be a copy in his/her private storage, so they can only edit his/her own copy.

![Dataset dashboards](https://github.com/cirisjl/Machine-learning-development-environment-for-single-cell-sequencing-data-analyses/assets/49490901/ed750c4f-3b9b-4411-bae5-a5e64522f9c6)

**Comment by karthikgou** [comment]
Functionality is implemented and hence closing the issue.

PR: https://github.com/cirisjl/Machine-learning-development-environment-for-single-cell-sequencing-data-analyses/pull/7
