### ISSUE TITLE
Test Integration task backend and add the frontend

### ISSUE THREAD

**Issue by cirisjl** [cirisjl/Machine-learning-development-environment-for-single-cell-sequencing-data-analyses#14]
I have pushed the code for Integration to Git. However, I didn't have time to modify the **create_integration_task_async** function in **api/routers/tools.py**. It's different from the others since the input is not a single dataset but a list of datasets. 

Please modify the code, test it, and add it to the front end.

Thanks!

**Comment by karthikgou** [comment]
Integrated all the methods for integration.

PR: https://github.com/cirisjl/Machine-learning-development-environment-for-single-cell-sequencing-data-analyses/pull/17
